spring.application.name=epic-user-service

spring.jpa.hibernate.ddl-auto=validate

spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

spring.datasource.driver-class-name=org.postgresql.Driver
